name: ion_token_analytics
description: A Dart Library for ION Token Analytics client
version: 0.0.1
homepage: null

environment:
  sdk: ^3.9.2

dependencies:
  crypto: ^3.0.7
  freezed_annotation: ^2.4.1
  http2: ^2.3.1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.2
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  test: ^1.26.0
  very_good_analysis: ^6.0.0

dependency_overrides:
  analyzer_plugin: ^0.13.1
