name: ion_token_analytics
description: A Dart Library for ION Token Analytics client
version: 0.0.1
homepage: null

environment:
  sdk: ^3.9.2

dependencies:
  crypto: ^3.0.7
  http2: ^2.3.1

dev_dependencies:
  custom_lint: ^0.8.1
  test: ^1.27.0
  very_good_analysis: ^6.0.0
