name: ion
description: ION App

publish_to: "none"

version: 9.9.9+9999

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: "3.35.3"

dependencies:
  android_id: ^0.4.0
  android_play_install_referrer: ^0.4.0
  app_badge_plus: ^1.2.3
  app_links: ^6.4.0
  appsflyer_sdk:
    git:
      url: https://github.com/ice-blockchain/appsflyer-flutter-plugin.git
      ref: master
  async: ^2.11.0
  audio_waveforms: ^1.3.0
  back_button_interceptor: ^7.0.3
  bech32: ^0.2.2
  blurhash_ffi: ^1.2.7
  btc_address_validate_swan: ^1.2.1
  cached_network_image: ^3.4.1
  cached_video_player_plus: ^4.0.1
  camera: ^0.11.2
  camera_android_camerax: ^0.6.19
  carousel_slider: ^5.0.0
  charcode: ^1.4.0
  collection: ^1.18.0
  convert: ^3.1.2
  cross_file: ^0.3.4+2
  cryptography: ^2.7.0
  cryptography_flutter:
    git:
      url: https://github.com/zkrige/cryptography.git
      path: cryptography_flutter
      ref: 9893cd9
  cupertino_icons: ^1.0.6
  custom_refresh_indicator: ^4.0.1
  decimal: ^3.2.4
  device_info_plus: ^11.1.0
  dio: ^5.7.0
  dio_http2_adapter:
    git:
      url: https://github.com/ice-blockchain/dio.git
      path: plugins/http2_adapter
  dio_smart_retry: ^7.0.1
  dlibphonenumber: ^1.1.26
  dots_indicator: ^3.0.1
  dotted_border: ^2.1.0
  drift: ^2.28.1
  drift_db_viewer: ^2.1.0
  drift_flutter: ^0.2.5
  email_validator: ^3.0.0
  es_compression: ^2.0.14
  extended_text: ^15.0.2
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  external_app_launcher: ^4.0.3
  facebook_app_events: ^0.21.0
  ffmpeg_kit_flutter:
    git:
      url: https://github.com/ice-blockchain/ffmpeg-kit
      path: flutter/flutter
      ref: main
  file: ^7.0.1
  file_picker: ^8.1.2
  file_saver: ^0.2.12
  filesize: ^2.0.1
  firebase_analytics:
    git:
      url: https://github.com/ice-blockchain/flutterfire.git
      path: packages/firebase_analytics/firebase_analytics
  firebase_core:
    git:
      url: https://github.com/ice-blockchain/flutterfire.git
      path: packages/firebase_core/firebase_core
  firebase_messaging:
    git:
      url: https://github.com/ice-blockchain/flutterfire.git
      path: packages/firebase_messaging/firebase_messaging
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.4.1
  flutter_command: ^7.2.2
  flutter_hooks: ^0.20.5
  flutter_inappwebview: ^6.1.5
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications:
    git:
      url: https://github.com/ice-blockchain/flutter_local_notifications.git
      path: flutter_local_notifications
      ref: feature/clear-notifications
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^11.4.2
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.2.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.16
  freezed_annotation: ^2.4.1
  functional_listener: ^4.1.0
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  googleapis: ^13.2.0
  gradient_borders: ^1.0.2
  hooks_riverpod: ^2.6.1
  http: ^1.6.0
  icloud_storage: ^2.2.0
  image: ^4.7.2
  image_cropper: ^11.0.0
  in_app_update: ^4.2.5
  intl: any
  ion_connect_cache:
    path: packages/ion_connect_cache
  ion_content_labeler:
    path: packages/ion_content_labeler
  ion_identity_client:
    path: packages/ion_identity_client
  ion_screenshot_detector:
    path: packages/ion_screenshot_detector
  ion_swap_client:
    path: packages/ion_swap_client
  ion_token_analytics:
    path: packages/ion_token_analytics
  isolate_manager: ^6.1.0
  json_annotation: ^4.8.1
  lottie: ^3.1.0
  markdown: ^7.3.0
  markdown_quill:
    git:
      url: https://github.com/ice-blockchain/markdown_quill
      ref: 5d8aaecb8d8d7425ccf3bd5753b751af8628b1e8
  meta: ^1.15.0
  mime: ^2.0.0
  mocktail: ^1.0.4
  nip44:
    git:
      url: https://github.com/ice-blockchain/dart-nip44.git
      ref: 1.1.0
  nostr_dart:
    git:
      url: https://github.com/ice-blockchain/nostr-dart
      ref: 0.0.41
  ogp_data_extract: ^0.1.4
  open_filex: ^4.4.0
  package_info_plus: ^8.3.0
  palette_generator: ^0.3.3+5
  path: ^1.9.0
  path_provider: ^2.1.4
  path_provider_foundation: ^2.4.1
  permission_handler: ^11.3.0
  photo_manager: ^3.6.3
  photo_manager_image_provider: ^2.1.1
  pinenacl: ^0.6.0
  qr_code_scanner_plus: ^2.0.10+1
  qr_flutter: ^4.1.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  screenshot: ^3.0.0
  sensors_plus: ^6.1.1
  sentry_flutter: ^8.14.2
  share_plus: ^10.0.2
  shared_preferences: ^2.3.5
  shared_preferences_foundation: ^2.5.4
  shared_preferences_platform_interface: ^2.4.1
  shimmer: ^3.0.0
  showcaseview: ^4.0.1
  smooth_sheets: ^0.14.0
  social_sharing_plus: ^1.2.3
  stream_transform: ^2.1.1
  super_sliver_list: ^0.4.1
  synchronized: ^3.3.0+3
  talker_dio_logger: 4.7.1
  talker_flutter: 4.7.1
  talker_riverpod_logger: 4.7.1
  tflite_flutter: ^0.12.1
  timeago: ^3.6.1
  uri_to_file: ^1.0.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  video_player: ^2.10.0
  video_player_win: ^2.3.11
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.2.11
  web3dart: ^2.7.3
  window_manager: ^0.4.2

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.2
  drift_dev: ^2.28.0
  flutter_gen: ^5.8.0
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  go_router_builder: ^3.0.1
  ion_lint_rules:
    path: packages/ion_lint_rules
  json_serializable: ^6.7.1
  melos: ^6.1.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  sentry_dart_plugin: ^2.4.1
  very_good_analysis: ^6.0.0
  video_player_platform_interface: ^6.3.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Black.ttf
        - asset: assets/fonts/NotoSans-BlackItalic.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
        - asset: assets/fonts/NotoSans-ExtraBold.ttf
        - asset: assets/fonts/NotoSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/NotoSans-ExtraLight.ttf
        - asset: assets/fonts/NotoSans-ExtraLightItalic.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
        - asset: assets/fonts/NotoSans-Light.ttf
        - asset: assets/fonts/NotoSans-LightItalic.ttf
        - asset: assets/fonts/NotoSans-Medium.ttf
        - asset: assets/fonts/NotoSans-MediumItalic.ttf
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-SemiBold.ttf
        - asset: assets/fonts/NotoSans-SemiBoldItalic.ttf
        - asset: assets/fonts/NotoSans-Thin.ttf
        - asset: assets/fonts/NotoSans-ThinItalic.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
    - family: Monaco
      fonts:
        - asset: assets/fonts/Monaco.ttf
  assets:
    - lib/app/templates/basic.json
    - assets/videos/
    - assets/lottie/
    - assets/svg/
    - assets/svg/networks/
    - assets/svg/avatars/
    - assets/svg/logo/
    - assets/images/
    - assets/images/bg/
    - assets/images/qr_code/
    - assets/images/notifications/
    - assets/images/invite_friends/
    - assets/images/tokenized_communities/
    - assets/images/ads/
    - assets/emoji_data_sets/emojis-by-group.json
    - assets/emoji_data_sets/emoji-keywords.json
    - assets/ion_identity/coins.json
    - assets/ion_identity/coins_version.txt
    - assets/ion_identity/networks.json
    - assets/ml/nsfw_int8.tflite
    - assets/ml/nsfw_labels.txt

flutter_gen:
  output: lib/generated/

  integrations:
    lottie: true

# Because every version of ion_identity_client from path depends on passkeys ^2.0.9 and no versions of passkeys match >2.0.9 <3.0.0, every version of ion_identity_client from path requires passkeys 2.0.9.
# And because passkeys 2.0.9 depends on passkeys_web ^2.0.2, every version of ion_identity_client from path requires passkeys_web ^2.0.2.
# Because passkeys_web 2.0.2 depends on js ^0.7.1 and no versions of passkeys_web match >2.0.2 <3.0.0, passkeys_web ^2.0.2 requires js ^0.7.1.
# Thus, every version of ion_identity_client from path requires js ^0.7.1.
# And because qr_code_scanner 1.0.1 depends on js ^0.6.3 and no versions of qr_code_scanner match >1.0.1 <2.0.0, ion_identity_client from path is incompatible with qr_code_scanner ^1.0.1.
# So, because ice depends on both qr_code_scanner ^1.0.1 and ion_identity_client from path, version solving failed.
dependency_overrides:
  analyzer_plugin: ^0.13.1
  flutter_quill: ^11.4.2
  js: ^0.7.1

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: ion-app-testnet
  org: sentry
