# pubspec.yaml
name: ion_lint_rules
environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  # we will use analyzer for inspecting Dart files
  analyzer: any
  analyzer_plugin: any
  # custom_lint_builder will give us tools for writing lints
  custom_lint_builder: ^0.7.3
  flutter_test:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^6.0.0
