name: ion_swap_client
description: "Swap and bridge client for ION"
version: 0.0.1

publish_to: none

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  convert: ^3.1.1
  cryptography: ^2.7.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  http: ^1.3.0
  intl: any
  ion_identity_client:
    path: ../ion_identity_client
  json_annotation: ^4.9.0
  rxdart: ^0.28.0
  tonutils: ^0.5.7
  web3dart: ^2.7.3

flutter:
  assets:
    - assets/json/okx_ids.json

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0