name: ion_connect_cache
description: A cache service for ION Connect event messages using Drift database.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  collection: ^1.18.0
  drift: ^2.28.1
  meta: ^1.15.0
  nostr_dart:
    git:
      url: https://github.com/ice-blockchain/nostr-dart
      ref: 0.0.41

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.2
  drift_dev: ^2.28.0
  lints: ^5.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
