name: ion_content_labeler
description: "The plugin might be used to analyze the input text and produce
  corresponding labels, such as the detected language and content categories"
version: 0.0.1
homepage: null

environment:
  sdk: ^3.6.2
  flutter: '>=3.3.0'

resolution: workspace

dependencies:
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  http: ^1.3.0
  path_provider: ^2.1.5

dev_dependencies:
  custom_lint: ^0.7.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - assets/language_identification.176.ftz
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
