name: receive_sharing
description: Receives shared text (and later media) from other apps via receive_sharing_intent. Android only for now.
version: 1.0.0

publish_to: none

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent.git
      ref: master
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.2
  lints: ^5.0.0
  riverpod_generator: ^2.6.1
  test: ^1.24.0
  very_good_analysis: ^6.0.0
