name: ion_ads
description: Ads SDK wrapper and UI components (Appodeal native ads) for ION.
version: 0.1.0

publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  custom_lint: ^0.7.2
  lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.appodeal.appodeal_flutter
        pluginClass: IonAppodealFlutterPlugin
      ios:
        pluginClass: IonAppodealFlutterPlugin

  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Light.ttf
        - asset: assets/fonts/NotoSans-Medium.ttf
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-SemiBold.ttf
  assets:
    - assets/images/


false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist

